### ISSUE TITLE
Response not successful: Received status code 500

### ISSUE THREAD

**Issue by kickbk** [RudolfBenadie/apollo-datasource-firebase#28]
Hi Rudolph. Thanks a lot for sharing this datasource.
I am not sure, but I think your example in Readme has an error. In `getUsers`, shouldn't it be `var usersListResult = await this.getPageOfUsers({ pageSize, pageToken });` and not `getUsersList`? I don't see `getUsersList` in `index.js` anywhere.

Also, I am trying to set up a basic Apollo server with your lib, but I'm getting `"error": "Response not successful: Received status code 500"` in playground.

What I did is this:

* `yarn add apollo-datasource-firebase`
* Added a `firebaseConfig.json` with the required credentials (they're valid. I tested elsewhere.)
* added a `users.js` as instructed (minus the correction I mentioned above)

and then finally my index.js:

```
const { ApolloServer, gql } = require("apollo-server");
const UsersAPI = require("./users");

const typeDefs = gql`
  type User {
    id: ID!
    phoneNumber: String
  }
  type Query {
    users: [User]
  }
`;
const resolvers = {
  Query: {
    users: async (_source, { pageSize, pageToken }, { dataSources }) => {
      return dataSources.usersAPI.getPageOfUsers(pageSize, pageToken);
    },
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => {
    return {
      usersAPI: new UsersAPI(),
    };
  },
  introspection: true,
});

server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`);
});
```

Do you know why it's not connecting for me?

**Comment by RudolfBenadie** [comment]
Hi kickbk,

The function dataSources.usersAPI.getPageOfUsers returns a promise, I think that is why you are experiencing this issue.  Try to change your code as follows:

```
const resolvers = {
  Query: {
    users: async (_source, { pageSize, pageToken }, { dataSources }) => {
      return await dataSources.usersAPI.getPageOfUsers(pageSize, pageToken);
    },
  },
};
```
Let me know if it works then I can close this issue.

PS. You are correct about the documentation, fixing it.

**Comment by kickbk** [comment]
That didn't work, although you are right I forgot to await the response. The issue happens in the initialization of the playground using the firebase connection. So if I remove the Query altogether, I still get the same error.
I will debug first thing after the weekend and get back to you. If it's working for you, then it must be something with my settings/setup that is incorrect.

**Comment by RudolfBenadie** [comment]
Resolved
